"""add timestamp column

Revision ID: 794451c8fa68
Revises: 5966594be78b
Create Date: 2025-03-10 23:30:41.080084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794451c8fa68'
down_revision = '5966594be78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_watch_list_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('added_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_at', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_watch_list_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
