"""added backdrop path to db

Revision ID: 9b17dc2938fb
Revises: 794451c8fa68
Create Date: 2025-03-11 16:52:58.419245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b17dc2938fb'
down_revision = '794451c8fa68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backdrop_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_list', schema=None) as batch_op:
        batch_op.drop_column('backdrop_path')

    # ### end Alembic commands ###
